language: node_js
node_js: 12

stages:
  - test

jobs:
  include:

    - stage: test_api
      services:
        - mongodb
      env:
        - JARDI_TEST_MONGO_URI="mongodb://127.0.0.1:27017/jardin?retryWrites=true&w=majority" JARDI_TEST_ADMIN_MONGO_DB_NAME=jardinAdmin
      script:
        - npm install
        - npm run travis-test
      after_script:
        - ls /home/travis/.npm/_logs/*
        - cat /home/travis/.npm/_logs/*-debug.log
